"""
WeCare — Security Infrastructure (STEPS 5-6)

Password hashing:   bcrypt (PASSWORD_BCRYPT compatible)
JWT:                HS256 via PyJWT (compatible with manual HS256 in jwt)

constants:
    ACCESS_TOKEN_EXPIRE  = 3600    (1 hour)
    REFRESH_TOKEN_EXPIRE = 604800  (7 days)

jwt payload:
    { user_id, role, type, iat, exp }
"""

import time
from typing import Any, Optional

import bcrypt
import jwt

from app.core.config import get_settings

# ── Token expiration (from config/constants L20-21) ──
ACCESS_TOKEN_EXPIRE: int = 3600
REFRESH_TOKEN_EXPIRE: int = 604800


# ══════════════════════════════════════════════════════════
# Password Hashing — PASSWORD_BCRYPT parity
# ══════════════════════════════════════════════════════════

def hash_password(plain: str) -> str:
    """
    password_hash($password, PASSWORD_BCRYPT)

    Returns a bcrypt hash string compatible with password_verify().
    """
    return bcrypt.hashpw(plain.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def verify_password(plain: str, hashed: str) -> bool:
    """
    password_verify($password, $hash)

    Verifies a plaintext password against a bcrypt hash.
    Compatible with hashes generated by or Python.
    """
    try:
        return bcrypt.checkpw(plain.encode("utf-8"), hashed.encode("utf-8"))
    except Exception:
        return False


# ══════════════════════════════════════════════════════════
# JWT — jwt parity (HS256)
# ══════════════════════════════════════════════════════════

def create_jwt(payload: dict, expire_seconds: int) -> str:
    """
    generate_token($payload, $expire_seconds)

    Creates an HS256 JWT with iat/exp claims.
    Payload from login L95-99:
        { user_id, role, type: "access"|"refresh" }
    """
    settings = get_settings()
    now = int(time.time())
    token_payload = {
        **payload,
        "iat": now,
        "exp": now + expire_seconds,
    }
    return jwt.encode(token_payload, settings.JWT_SECRET, algorithm="HS256")


def decode_jwt(token: str) -> Optional[dict]:
    """
    verify_token($token)

    Returns the decoded payload or None on any failure:
    - invalid signature
    - expired
    - malformed

    jwt returns false on failure; we return None.
    """
    settings = get_settings()
    try:
        return jwt.decode(token, settings.JWT_SECRET, algorithms=["HS256"])
    except jwt.ExpiredSignatureError:
        return None
    except jwt.InvalidTokenError:
        return None


def create_token_pair(user_id: int, role: str) -> tuple[str, str]:
    """
    Creates access + refresh token pair matching login L95-105.

    Returns: (access_token, refresh_token)
    """
    access = create_jwt(
        {"user_id": user_id, "role": role, "type": "access"},
        ACCESS_TOKEN_EXPIRE,
    )
    refresh = create_jwt(
        {"user_id": user_id, "role": role, "type": "refresh"},
        REFRESH_TOKEN_EXPIRE,
    )
    return access, refresh
